name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Add nuget source
        run: dotnet nuget add source ${{ secrets.NUGET_URL }} -u ${{ secrets.NUGET_USER }} -p ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text

      - name: Build project
        run: dotnet build --configuration Release

      - name: Create package
        run: dotnet pack --configuration Release

      - name: Publish package
        run: dotnet nuget push "./bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s ${{ secrets.NUGET_URL }}
